# Generated by Django 3.2.18 on 2024-09-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_subcategory_title_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='tags',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
