# Generated by Django 3.2.18 on 2024-09-28 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240918_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategoryMetaTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.SlugField(blank=True, null=True, unique=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_titles', to='store.subcategory')),
            ],
        ),
    ]
